name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            submodules: true

        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
                node-version: '20'

        - name: Install dependencies
          run: |
              cd frontend
              yarn

        - name: Build
          run: |
              cd frontend
              yarn build

        - name: Archive production artifacts
          uses: actions/upload-artifact@v4
          with:
              name: Server
              path: |
                  frontend/dist/
                  server.py
                  README.md
                  LICENSE